-- Products Table (if not exists)
create table if not exists public.products (
  id uuid default uuid_generate_v4() primary key,
  sku text not null unique,
  name text not null,
  price numeric not null,
  stock_quantity integer default 0,
  marketplace_sync_status jsonb default '{}'::jsonb, -- { "shopee": "synced", "ml": "pending" }
  created_at timestamp with time zone default now()
);

-- Marketplace Suggestions (generated by Agent)
create table if not exists public.marketplace_suggestions (
  id uuid default uuid_generate_v4() primary key,
  product_id uuid references public.products(id),
  suggested_price numeric,
  strategy text,
  reason text,
  created_at timestamp with time zone default now()
);

-- Security Logs (Audit)
create table if not exists public.audit_logs (
  id uuid default uuid_generate_v4() primary key,
  actor text,
  action text,
  resource text,
  risk_level text,
  created_at timestamp with time zone default now()
);

-- RLS
alter table public.products enable row level security;
alter table public.marketplace_suggestions enable row level security;
alter table public.audit_logs enable row level security;

create policy "Enable read access for all users" on "public"."products" for select using (true);
create policy "Enable insert for authenticated users only" on "public"."products" for insert with check (auth.role() = 'authenticated');
